---
- name: 'Install cowsay for fun'
  hosts: 127.0.0.1
  remote_user: root
  become: false

  tasks:
    - name: Install - perl
      community.general.apk:
        name: perl
        state: present

    - name: Install - cowsay
      community.general.apk:
        name: cowsay
        state: latest
        update_cache: true
        repository: http://dl-cdn.alpinelinux.org/alpine/edge/testing