---
name: Build and Push - Docker
description: Builds and pushes docker image to Docker Hub via Packer
inputs:
  packer-path:
    required: true
    description: "Path to packer file"
  docker-username:
    required: true
    description: "Docker Hub username"
  docker-token:
    required: true
    description: "Docker Hub PAT"

runs:
  using: "composite"
  steps:
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"

    - name: Run `packer init`
      id: init
      shell: bash
      run: "packer init ${{ inputs.packer-path }}"

    - name: Run `packer validate`
      id: validate
      shell: bash
      run: "packer validate ${{ inputs.packer-path }}"

    - name: Build Artifact
      shell: bash
      env:
        PKR_VAR_docker_username: ${{ secrets.DOCKER_USERNAME }}
        PKR_VAR_docker_token: ${{ secrets.DOCKER_PASS }}
      run: |
        packer build -on-error=abort \
          -var "docker_username='$PKR_VAR_docker_username'" \
          -var "docker_token='$PKR_VAR_docker_token'" \
          ${{ inputs.packer-path }}