---
name: Build and Push - Docker
description: Builds and pushes docker image to Docker Hub via Packer
inputs:
  dockerhub-server:
    required: true
    description: "Docker Hub base URL"
  dockerhub-username:
    required: true
    description: "Docker Hub username"
  dockerhub-token:
    required: true
    description: "Docker Hub password (PAT)"
  packer-path:
    required: true
    description: "Path to packer file"

runs:
  using: "composite"
  steps:
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"

    - name: Run `packer init`
      id: init
      shell: bash
      run: "packer init ${{ inputs.packer-path }}"

    - name: Run `packer validate`
      id: validate
      shell: bash
      run: "packer validate ${{ inputs.packer-path }}"

    - name: Build Artifact
      shell: bash
      run: "packer build -color=false -on-error=abort ${{ inputs.packer-path }}"
      env:
        PKR_VAR_docker_server: ${{ input.dockerhub-server }}
        PKR_VAR_docker_username: ${{ inputs.dockerhub-username }}
        PKR_VAR_docker_token: ${{ inputs.dockerhub-token }}